version: 2
jobs:
  subscribe:
    docker:
      - image: node:8
    steps:
      - run: npm run slack

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - subscribe
